server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: Spring Cloud Gateway GlobalFilter Message
            showPreLogger: true
            showPostLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/open/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
              args:
                hasUserRole: true
                hasBrandRole: false
                hasAdminRole: false

        - id: brand-service
          uri: lb://BRAND-SERVICE
          predicates:
            - Path=/brand-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/brand-service/(?<segment>.*), /$\{segment}
        - id: brand-service
          uri: lb://BRAND-SERVICE
          predicates:
            - Path=/brand-service/open/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/brand-service/(?<segment>.*), /$\{segment}
        - id: brand-service
          uri: lb://BRAND-SERVICE
          predicates:
            - Path=/brand-service/admin/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/brand-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
              args:
                hasUserRole: false
                hasBrandRole: false
                hasAdminRole: true
        - id: brand-service
          uri: lb://BRAND-SERVICE
          predicates:
            - Path=/brand-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/brand-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
              args:
                hasUserRole: false
                hasBrandRole: true
                hasAdminRole: false

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/open/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/admin-service/(?<segment>.*), /$\{segment}
            - name: AuthorizationHeaderFilter
              args:
                hasUserRole: false
                hasBrandRole: false
                hasAdminRole: true

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transaction-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/transaction-service/(?<segment>.*), /$\{segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
